server:
  port: 8081
  servlet:
    context-path: /spreadsheet

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: spreadsheet
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://sql10.freesqldatabase.com:3306/sql10440821?useTimezone=true&serverTimezone=UTC
    username: sql10440821
    password: 5Chen52ZPx

rabbitmq:
  exchange: spreadsheet
  queue: pampacare
  routingKey: spreadsheet-ms